-- MySQL Script generated by MySQL Workbench
-- Thu Mar  1 22:07:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yueli
-- -----------------------------------------------------
-- 悦历 app 数据库

-- -----------------------------------------------------
-- Schema yueli
--
-- 悦历 app 数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yueli` DEFAULT CHARACTER SET utf8 ;
USE `yueli` ;

-- -----------------------------------------------------
-- Table `yueli`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`user` ;

CREATE TABLE IF NOT EXISTS `yueli`.`user` (
  `user_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户 ID',
  `username` VARCHAR(32) NOT NULL COMMENT '用户名',
  `nickname` VARCHAR(32) NOT NULL DEFAULT '悦历用户' COMMENT '昵称',
  `password` CHAR(32) NOT NULL COMMENT '密码',
  `signature` VARCHAR(64) NOT NULL DEFAULT 'TA什么都没写' COMMENT '性别',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
COMMENT = '用户';


-- -----------------------------------------------------
-- Table `yueli`.`spot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`spot` ;

CREATE TABLE IF NOT EXISTS `yueli`.`spot` (
  `spot_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '景点 ID',
  `name` VARCHAR(64) NOT NULL COMMENT '景点名称',
  `description` TEXT NOT NULL COMMENT '景点信息',
  `city` VARCHAR(32) NOT NULL COMMENT '所在城市',
  `location` JSON NOT NULL COMMENT '景点地点',
  PRIMARY KEY (`spot_id`),
  UNIQUE INDEX `spot_id_UNIQUE` (`spot_id` ASC))
ENGINE = InnoDB
COMMENT = '景点';


-- -----------------------------------------------------
-- Table `yueli`.`spot_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`spot_rank` ;

CREATE TABLE IF NOT EXISTS `yueli`.`spot_rank` (
  `spot_id` BIGINT UNSIGNED NOT NULL COMMENT '评哪个景点',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '哪个用户评的',
  `rank` TINYINT NOT NULL COMMENT '评分',
  UNIQUE INDEX `spot_user_idx` (`spot_id` ASC, `user_id` ASC),
  CONSTRAINT `spot_rank_spot_id_fk`
    FOREIGN KEY (`spot_id`)
    REFERENCES `yueli`.`spot` (`spot_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `spot_rank_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `yueli`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '景点评分记录。某景点的评分从该表动态计算得出';


-- -----------------------------------------------------
-- Table `yueli`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`comment` ;

CREATE TABLE IF NOT EXISTS `yueli`.`comment` (
  `comment_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论 ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '评论者',
  `reply_to_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '回复先前的哪条评论。NULL 表示是新评论',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '发表时间',
  `content` TEXT NOT NULL COMMENT '评论内容',
  PRIMARY KEY (`comment_id`),
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC),
  INDEX `comment_user_id_fk_idx` (`user_id` ASC),
  INDEX `comment_reply_to_id_fk_idx` (`reply_to_id` ASC),
  CONSTRAINT `comment_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `yueli`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `comment_reply_to_id_fk`
    FOREIGN KEY (`reply_to_id`)
    REFERENCES `yueli`.`comment` (`comment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '评论';


-- -----------------------------------------------------
-- Table `yueli`.`travel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`travel` ;

CREATE TABLE IF NOT EXISTS `yueli`.`travel` (
  `travel_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '游记 ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '作者',
  `title` VARCHAR(64) NOT NULL COMMENT '游记标题',
  `first_day` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '第一天是哪天',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0未被删除，1已被删除',
  PRIMARY KEY (`travel_id`),
  UNIQUE INDEX `travel_id_UNIQUE` (`travel_id` ASC),
  INDEX `travel_user_id_fk_idx` (`user_id` ASC),
  CONSTRAINT `travel_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `yueli`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '游记';


-- -----------------------------------------------------
-- Table `yueli`.`travel_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`travel_record` ;

CREATE TABLE IF NOT EXISTS `yueli`.`travel_record` (
  `travel_record_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '游记记录 ID',
  `travel_id` BIGINT UNSIGNED NOT NULL COMMENT '属于哪一个游记',
  `spot_id` BIGINT UNSIGNED NOT NULL COMMENT '哪个景点',
  `content` TEXT NOT NULL COMMENT '记录内容',
  `photo_description` VARCHAR(64) NULL COMMENT '照片描述',
  `time` TIMESTAMP NOT NULL COMMENT '发表时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0未被删除，1已被删除',
  PRIMARY KEY (`travel_record_id`),
  UNIQUE INDEX `travel_record_id_UNIQUE` (`travel_record_id` ASC),
  INDEX `travel_record_travel_id_fk_idx` (`travel_id` ASC),
  INDEX `travel_record_spot_id_fk_idx` (`spot_id` ASC),
  CONSTRAINT `travel_record_travel_id_fk`
    FOREIGN KEY (`travel_id`)
    REFERENCES `yueli`.`travel` (`travel_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `travel_record_spot_id_fk`
    FOREIGN KEY (`spot_id`)
    REFERENCES `yueli`.`spot` (`spot_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '游记的每一次记录';


-- -----------------------------------------------------
-- Table `yueli`.`spot_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`spot_comment` ;

CREATE TABLE IF NOT EXISTS `yueli`.`spot_comment` (
  `comment_id` BIGINT UNSIGNED NOT NULL COMMENT '评论',
  `spot_id` BIGINT UNSIGNED NOT NULL COMMENT '评论的是哪个景点',
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC),
  INDEX `spot_comment_spot_id_fk_idx` (`spot_id` ASC),
  CONSTRAINT `spot_comment_comment_id_fk`
    FOREIGN KEY (`comment_id`)
    REFERENCES `yueli`.`comment` (`comment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `spot_comment_spot_id_fk`
    FOREIGN KEY (`spot_id`)
    REFERENCES `yueli`.`spot` (`spot_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '评论和景点的关联';


-- -----------------------------------------------------
-- Table `yueli`.`user_follower`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`user_follower` ;

CREATE TABLE IF NOT EXISTS `yueli`.`user_follower` (
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '被关注者',
  `follower_id` BIGINT UNSIGNED NOT NULL COMMENT '粉丝',
  UNIQUE INDEX `user_follower_idx` (`user_id` ASC, `follower_id` ASC),
  UNIQUE INDEX `follower_user_idx` (`follower_id` ASC, `user_id` ASC),
  CONSTRAINT `user_follower_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `yueli`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_follower_follower_id_fk`
    FOREIGN KEY (`follower_id`)
    REFERENCES `yueli`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '用户关注另一个用户的关联表';


-- -----------------------------------------------------
-- Table `yueli`.`travel_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`travel_comment` ;

CREATE TABLE IF NOT EXISTS `yueli`.`travel_comment` (
  `comment_id` BIGINT UNSIGNED NOT NULL COMMENT '评论',
  `travel_id` BIGINT UNSIGNED NOT NULL COMMENT '评论的是哪个游记',
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC),
  INDEX `travel_comment_travel_id_fk_idx` (`travel_id` ASC),
  CONSTRAINT `travel_comment_comment_id_fk`
    FOREIGN KEY (`comment_id`)
    REFERENCES `yueli`.`comment` (`comment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `travel_comment_travel_id_fk`
    FOREIGN KEY (`travel_id`)
    REFERENCES `yueli`.`travel` (`travel_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '游记评论';


-- -----------------------------------------------------
-- Table `yueli`.`feeling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`feeling` ;

CREATE TABLE IF NOT EXISTS `yueli`.`feeling` (
  `feeling_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '心情 ID',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '作者',
  `content` TEXT NOT NULL COMMENT '内容',
  `longitude` FLOAT NOT NULL COMMENT '发送地的经度',
  `latitude` FLOAT NOT NULL COMMENT '发送地的纬度',
  `time` TIMESTAMP NOT NULL COMMENT '发表时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0未被删除，1已被删除',
  PRIMARY KEY (`feeling_id`),
  UNIQUE INDEX `feeling_id_UNIQUE` (`feeling_id` ASC),
  INDEX `feeling_user_id_fk_idx` (`user_id` ASC),
  CONSTRAINT `feeling_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `yueli`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '心情';


-- -----------------------------------------------------
-- Table `yueli`.`feeling_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`feeling_comment` ;

CREATE TABLE IF NOT EXISTS `yueli`.`feeling_comment` (
  `comment_id` BIGINT UNSIGNED NOT NULL COMMENT '评论',
  `feeling_id` BIGINT UNSIGNED NOT NULL COMMENT '评论的是哪个心情',
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC),
  INDEX `feeling_comment_feeling_id_fk_idx` (`feeling_id` ASC),
  CONSTRAINT `feeling_comment_comment_id_fk`
    FOREIGN KEY (`comment_id`)
    REFERENCES `yueli`.`comment` (`comment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `feeling_comment_feeling_id_fk`
    FOREIGN KEY (`feeling_id`)
    REFERENCES `yueli`.`feeling` (`feeling_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '心情的评论';


-- -----------------------------------------------------
-- Table `yueli`.`travel_favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`travel_favorite` ;

CREATE TABLE IF NOT EXISTS `yueli`.`travel_favorite` (
  `travel_id` BIGINT UNSIGNED NOT NULL COMMENT '被收藏的游记',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '谁收藏的',
  UNIQUE INDEX `travel_user_idx` (`travel_id` ASC, `user_id` ASC),
  UNIQUE INDEX `user_travel_idx` (`user_id` ASC, `travel_id` ASC),
  CONSTRAINT `travel_favorite_travel_id_fk`
    FOREIGN KEY (`travel_id`)
    REFERENCES `yueli`.`travel` (`travel_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `travel_favorite_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `yueli`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '游记收藏记录';


-- -----------------------------------------------------
-- Table `yueli`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`notification` ;

CREATE TABLE IF NOT EXISTS `yueli`.`notification` (
  `notification_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '消息 ID',
  `sender_id` BIGINT UNSIGNED NOT NULL COMMENT '消息的触发者',
  `type` ENUM('comment-comment', 'comment-travel', 'comment-feeling', 'follow-user', 'favorite-travel', 'post-travel', 'post-feeling') NOT NULL COMMENT '消息类型',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '消息发送时间',
  `content` JSON NOT NULL COMMENT '消息内容需要的元素',
  PRIMARY KEY (`notification_id`),
  UNIQUE INDEX `notification_id_UNIQUE` (`notification_id` ASC))
ENGINE = InnoDB
COMMENT = '消息';


-- -----------------------------------------------------
-- Table `yueli`.`notification_read`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`notification_read` ;

CREATE TABLE IF NOT EXISTS `yueli`.`notification_read` (
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '收消息的人',
  `notification_id` BIGINT UNSIGNED NOT NULL COMMENT '0未读，1已读',
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  UNIQUE INDEX `user_notification_idx` (`user_id` ASC, `notification_id` ASC),
  INDEX `notification_read_notification_id_fk_idx` (`notification_id` ASC),
  CONSTRAINT `notification_read_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `yueli`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `notification_read_notification_id_fk`
    FOREIGN KEY (`notification_id`)
    REFERENCES `yueli`.`notification` (`notification_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '消息已读记录';


-- -----------------------------------------------------
-- Table `yueli`.`spot_favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yueli`.`spot_favorite` ;

CREATE TABLE IF NOT EXISTS `yueli`.`spot_favorite` (
  `spot_id` BIGINT UNSIGNED NOT NULL COMMENT '被收藏的景点',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '谁收藏的',
  UNIQUE INDEX `user_spot_idx` (`user_id` ASC, `spot_id` ASC),
  INDEX `spot_favorite_spot_id_fk_idx` (`spot_id` ASC),
  CONSTRAINT `spot_favorite_spot_id_fk`
    FOREIGN KEY (`spot_id`)
    REFERENCES `yueli`.`spot` (`spot_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `spot_favorite_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `yueli`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '景点收藏记录';


-- -----------------------------------------------------
-- Data for table `yueli`.`spot`
-- -----------------------------------------------------
START TRANSACTION;
USE `yueli`;
INSERT INTO `yueli`.`spot` (`spot_id`, `name`, `description`, `city`, `location`) VALUES (1, '科帕卡巴纳海滩', '科帕卡巴纳海滩被称为世界上最有名的海滩，海岸沿线长达4.5公里，海水蔚蓝，浪花雪白，沙滩洁净松软，加上终年气温适宜戏水，游人络绎不绝。', '里约热内卢，巴西', '{}');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
